version: 2.0

jobs:
  test:
    docker:
      - image: circleci/openjdk:stretch
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    working_directory: ~/my-app
    
    steps:
      - checkout
          path: ~/my-app
      - run: mvn test

  build:
    docker:
      - image: circleci/openjdk:stretch
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    working_directory: ~/my-app
    steps:
      - checkout
          path: ~/my-app
      - run: mvn package

workflows:
  version: 2

  test-then-build:
    jobs:
      - test
      - build
